POST http://localhost:3000/users
Content-Type: application/json
 
{
    "firstName" : "TONY",
    "lastName" : "KING",
    "email" : "tikay404@gmail.com",
    "password" : "Password123#"
} 

POST http://localhost:3000/users/create-many
Content-Type: application/json
 
{ 
    "users": [
    {
    "firstName" : "Davian",
    "lastName" : "jnr",
    "email" : "Dave404@gmail.com",
    "password" : "Password123#"
    },
    {
    "firstName" : "Maestro",
    "lastName" : "Dev",
    "email" : "Maestro@gmail.com",
    "password" : "Password1234#"
   } 
 ]
}