POST https://mindstitch-notes-backend-6.onrender.com/notes
content-Type: application/json

{
    "title" : "Sunday School",
    "body" : "All about Jesus"
},
{
    "title" : "Flutter",
    "body" : "All about Programming"
}