PATCH http://localhost:3000/post
Content-Type: application/json

{
    "id": 9,
    "title": "NestJS-with-Teekay",
    "status":  "draft",
    "postType": "page",
    "content": "flutter content",
    "metaOptions": {
      "metaValue" : "{\"sideBarEnabled\": true, \"footerActive\": true}"
    },
    "tags": [1]
}